"""empty message

Revision ID: 0b1c69c5c294
Revises: 
Create Date: 2021-06-29 17:49:06.749838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1c69c5c294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'])
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'owner_id')
    # ### end Alembic commands ###
